title: Blog
url: "https://dendroenydris.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "github.com/dendroenydris"
footer_text: "dendroenydris 2024"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"